Home page
shanaHirani/Ehsan pull request #1
Opened 2021-10-01 23:49 UTC by shanaHirani

2021-10-02 00:58 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    fun getTowDayAgo(): String {
A typo here: Tow -> Two

2021-10-02 00:59 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +            Log.i("net erroe", it)
Please do not put space in tags, as it's not possible to find it by search in the Logcat

2021-10-02 00:59 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    fun getTowDayAgo(): String {
چرا من اینجوری شدم

2021-10-02 01:09 UTC, ehsanheidari67 requested changes

2021-10-02 01:09 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +class Repository @Inject constructor(val remoteDataSource: RemoteDataSource) {
Please use a meaningful name rather than a just general name. What repository??!!

2021-10-02 01:09 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    private fun getCityName(): String {
1- Why do you have a function that just returns "Sydney"?
2- Normally you shouldn't return texts in English. The texts should be translatable. So please use String Resourse

2021-10-02 01:09 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +            _newsList.value = it?.newsList
You need to handle HTTP errors here. For example check for status code with it.code (or something like that)

2021-10-02 01:43 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    fun getTowDayAgo(): String {
I don't know

2021-10-03 09:13 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    fun getTowDayAgo(): String {
done

2021-10-03 09:16 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +            Log.i("net erroe", it)
ok

2021-10-03 09:18 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +    private fun getCityName(): String {
I think in future maybe we need to do some thing with it, like get the city name from location or ...

2021-10-03 09:20 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/Repository.kt
> +class Repository @Inject constructor(val remoteDataSource: RemoteDataSource) {
what should I call it? like newsRepository?

2021-10-03 09:28 UTC, merged