Details page
shanaHirani/Ehsan pull request #3
Opened 2021-10-04 09:05 UTC by shanaHirani

please check my code

2021-10-04 11:03 UTC, ehsanheidari67 requested changes

2021-10-04 11:03 UTC, ehsanheidari67 commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +        _navigateToSelectedNews.value = null
Why this?

2021-10-05 00:44 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/NewsRepository.kt
> +    @ApplicationContext private val context: Context
done

2021-10-05 00:46 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/NewsRepository.kt
> +        return context.getString(R.string.Sydney)
done

2021-10-05 00:50 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageFragment.kt
> +        viewModel.toastMassage.observe(viewLifecycleOwner,{
ok

2021-10-05 01:04 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +        _navigateToSelectedNews.value = null
it has something to do when your app killed when it is in the back ground.
like you are in the home page ,then  you put your app in back ground. For pressure on ram OS kill your app. you want your app in for ground. OS make your app again. your view model create again. in some condition it could cause on wanted navigation.

2021-10-05 01:05 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/ui/homePage/HomePageViewModel.kt
> +        _navigateToSelectedNews.value = null
I refer you to udacity course

2021-10-05 01:06 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/NewsRepository.kt
>          return LocalDate.now()
it was not red in my computer

2021-10-05 01:14 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/NewsRepository.kt
> +class NewsRepository @Inject constructor(
class NewsRepository != NewsRepository.kt
آیا؟

2021-10-05 01:20 UTC, shanaHirani commented on Ehsan/app/src/main/java/com/jetbrains/handson/mpp/ehsan/data/repository/NewsRepository.kt
>              override fun onResponse(call: Call<AllNews>, response: Response<AllNews>) {
would you explain more?

2021-10-05 01:38 UTC, merged